-- AlterTable
ALTER TABLE "Profile" 
ADD COLUMN IF NOT EXISTS "username" TEXT,
ADD COLUMN IF NOT EXISTS "creatorStatus" TEXT NOT NULL DEFAULT 'founding_creator',
ADD COLUMN IF NOT EXISTS "about" TEXT,
ADD COLUMN IF NOT EXISTS "coverImageUrl" TEXT,
ADD COLUMN IF NOT EXISTS "introVideoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "tagline" TEXT,
ADD COLUMN IF NOT EXISTS "location" TEXT,
ADD COLUMN IF NOT EXISTS "languages" JSONB,
ADD COLUMN IF NOT EXISTS "primaryExpertise" TEXT,
ADD COLUMN IF NOT EXISTS "skills" JSONB,
ADD COLUMN IF NOT EXISTS "teachingLevels" JSONB,
ADD COLUMN IF NOT EXISTS "contentFormats" JSONB,
ADD COLUMN IF NOT EXISTS "experiences" JSONB,
ADD COLUMN IF NOT EXISTS "education" JSONB,
ADD COLUMN IF NOT EXISTS "certifications" JSONB,
ADD COLUMN IF NOT EXISTS "github" TEXT,
ADD COLUMN IF NOT EXISTS "portfolio" TEXT,
ADD COLUMN IF NOT EXISTS "contactMethod" TEXT DEFAULT 'email',
ADD COLUMN IF NOT EXISTS "businessEmail" TEXT,
ADD COLUMN IF NOT EXISTS "allowCollaboration" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "profileVisibility" TEXT NOT NULL DEFAULT 'PUBLIC',
ADD COLUMN IF NOT EXISTS "privacySettings" JSONB,
ADD COLUMN IF NOT EXISTS "usernameLastChangedAt" TIMESTAMP(3);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Profile_username_key" ON "Profile"("username");
